package bibliotech.view;

import bibliotech.dao.EmprestimoDAO;
import bibliotech.dao.LivroDAO;
import bibliotech.dao.UsuarioDAO;
import java.sql.SQLException;

/**
 *
 * @author patri
 */
public class emprestimoView extends javax.swing.JFrame {
    
    private void atualizarDataDevolucao() {
        try {
            java.util.Date dataRetirada = (java.util.Date) txtDataRetirada.getValue();
            if (dataRetirada != null) {
                java.util.Calendar cal = java.util.Calendar.getInstance();
                cal.setTime(dataRetirada);
                cal.add(java.util.Calendar.DAY_OF_MONTH, 7);
                txtDevolucao.setValue(cal.getTime());
            } else {
                txtDevolucao.setValue(null);
            }
        } catch (Exception e) {
            txtDevolucao.setValue(null);
        }
    }
    
    private void carregarCombos() {
        try {
            cmbUsuario.removeAllItems();
            listaUsuarios = usuarioDAO.listar();
            for (bibliotech.model.Usuario u : listaUsuarios) {
                cmbUsuario.addItem(u.getNome() + " (" + u.getTipo() + ")");
            }

            cmbLivro.removeAllItems();
            listaLivros = livroDAO.listarDisponiveis();
            for (bibliotech.model.Livro l : listaLivros) {
                cmbLivro.addItem(l.getTitulo() + " (disp: " + l.getQtdDisponivel() + ")");
            }
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar dados: " + ex.getMessage());
        }
    }
    
    private UsuarioDAO usuarioDAO = new UsuarioDAO();
    private LivroDAO livroDAO = new LivroDAO();
    private EmprestimoDAO emprestimoDAO = new EmprestimoDAO();

    private java.util.List<bibliotech.model.Usuario> listaUsuarios = new java.util.ArrayList<>();
    private java.util.List<bibliotech.model.Livro> listaLivros = new java.util.ArrayList<>();
    /**
     * Creates new form emprestimoView
     */
    public emprestimoView() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BiblioTech - Novo Empréstimo");
        
        carregarCombos();
        txtDataRetirada.addPropertyChangeListener("value", evt -> atualizarDataDevolucao());
        txtDevolucao.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblLivro = new javax.swing.JLabel();
        lblDataRetirada = new javax.swing.JLabel();
        txtDataRetirada = new javax.swing.JFormattedTextField();
        lblDevolucao = new javax.swing.JLabel();
        txtDevolucao = new javax.swing.JFormattedTextField();
        btnRegistrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        cmbUsuario = new javax.swing.JComboBox<>();
        cmbLivro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario.setText("Usuário");

        lblLivro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLivro.setText("Livro disponível");

        lblDataRetirada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataRetirada.setText("Data de retirada");

        txtDataRetirada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtDataRetirada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDevolucao.setText("Devolução prevista");

        txtDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtDevolucao.setEnabled(false);
        txtDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrar.setText("Registrar empréstimo");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        cmbUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cmbLivro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDevolucao)
                    .addComponent(lblDataRetirada)
                    .addComponent(lblLivro)
                    .addComponent(lblUsuario)
                    .addComponent(txtDataRetirada)
                    .addComponent(txtDevolucao)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(cmbUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbLivro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDataRetirada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDevolucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(17, 17, 17)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        int idxU = cmbUsuario.getSelectedIndex();
        int idxL = cmbLivro.getSelectedIndex();
        if (idxU < 0 || idxL < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione usuário e livro.");
            return;
        }
        if (txtDataRetirada.getValue() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Informe a data de retirada.");
            return;
        }
        try {
            java.util.Date dRet = (java.util.Date) txtDataRetirada.getValue();
            java.util.Date dDev = (java.util.Date) txtDevolucao.getValue();

            bibliotech.model.Emprestimo emp = new bibliotech.model.Emprestimo(
                    listaLivros.get(idxL),
                    listaUsuarios.get(idxU),
                    dRet.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate(),
                    dDev.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate()
            );
            emprestimoDAO.inserir(emp);
            javax.swing.JOptionPane.showMessageDialog(this, "Empréstimo registrado com sucesso!");
            carregarCombos(); // atualiza quantidades
            txtDataRetirada.setValue(null);
            txtDevolucao.setValue(null);
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao registrar: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emprestimoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emprestimoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emprestimoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emprestimoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emprestimoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbLivro;
    private javax.swing.JComboBox<String> cmbUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDataRetirada;
    private javax.swing.JLabel lblDevolucao;
    private javax.swing.JLabel lblLivro;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JFormattedTextField txtDataRetirada;
    private javax.swing.JFormattedTextField txtDevolucao;
    // End of variables declaration//GEN-END:variables
}
